### ISSUE TITLE
Optional flake8-bugbear B9* Codes unusable with flakeheaven

### ISSUE THREAD

**Issue by Cielquan** [flakeheaven/flakeheaven#106]
I wanted to switch from pycodestyle's E501 to bugbear's B950. Both check the line-length, but B950 is more lenient.

But when I configure flakeheaven to do this, nothing happens.

```toml
[tool.flakeheaven]
max_line_length = 1

[tool.flakeheaven.plugins]
flake8-bugbear = ["+*"]
pycodestyle = ["+*", "-E501"]
```

This snippet should trigger B003 for the 4th line and B950 for line 1 and 4, because line-length is only 1. But no B950.
```python
import os


os.environ = []
```

---

I looked into bugbear's code and found the `should_warn` method which returns `False` for all instances of B950. In it's docstring stands:

> Returns `True` if Bugbear should emit a particular warning.
>
> flake8 overrides default ignores when the user specifies
`ignore = ` in configuration.  This is problematic because it means
specifying anything in `ignore = ` implicitly enables all optional
warnings.  This function is a workaround for this behavior.
>
> As documented in the README, the user is expected to explicitly select
the warnings.
>
> NOTE: This method is deprecated and will be removed in a future release. It is
recommended to use `extend-ignore` and `extend-select` in your flake8
configuration to avoid implicitly altering selected and ignored codes.

`should_warn`: https://github.com/PyCQA/flake8-bugbear/blob/b1e4ef296ec6afb6df788d81db0953cf5fd79566/bugbear.py#L131-L145

I did not look into flakeheaven's code, but my guess is, that flakeheaven somehow directly or indirectly uses this implicit activation mechanic, which result's in bugbear's B9* code not being usable.

**Comment by pwoolvett** [comment]
from [here](https://github.com/PyCQA/flake8-bugbear#how-to-enable-opinionated-warnings), it says those warnings should be explicitly activated.

```toml
[tool.flakeheaven]
max_line_length = 1
extend-select = ["B950"]
```

```py
# code.py - empty file with just this comment

```
 When run (`main` branch), I get:
 
```console
$ flakeheaven lint code.py
asdf.py:1:46: B950 line too long (45 > 1 characters) [flake8-bugbear]
  # code.py - empty file with just this comment
                                               ^
```

@Cielquan can we close this?

**Comment by Cielquan** [comment]
@pwoolvett Sorry for the late reply.

Unfortunately I cannot reproduce your behavior. When I copy your two snippets into files and run flakeheaven I get:

```console
$ python3.8 -m venv venv_test
$ . venv_test/bin/activate
$ pip install git+https://github.com/flakeheaven/flakeheaven@24f3ba08b9fc4d798d61c3a10b6a07a6a70e4817
$ flakeheaven lint code.py
code.py:1:2: E501 line too long (45 > 1 characters) [pycodestyle]
```

Even when I deactivate pycodestyle via the plugins settings it does not work. It simply no longer prints the E501 error.

```toml
[tool.flakeheaven]
max_line_length = 1
extend-select = ["B950"]

[tool.flakeheaven.plugins]
pycodestyle = ["-*"]
```

`ignore` and `extend-ignore` are ignored by flakeheaven ([docs ref](https://flakeheaven.readthedocs.io/en/latest/config.html#ignored-options)) so this is no option to deactivate E501 on another way.

---

I read bugbear's docs before writing the OP and also the part where you link to. There also stands:
> Some of Bugbear's checks require other flake8 checks disabled - e.g. E501 must be disabled when enabling B950.

So I am kind of confused that your proposed config actually works for you.

PS: I cannot reopen the issue 🤷🏾‍♂️

**Comment by pwoolvett** [comment]
`extend-select` != `extend_select`. My bad.

Using `
flakeheaven==2.0.0`
```tom
[tool.flakeheaven]
max_line_length = 1
extend_select = ["B950"]

[tool.flakeheaven.plugins]
flake8-bugbear = ["+*"]
```
Please try `FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint code.py` again.
I believe at the time I was working on #108, which could explay why it did trigger for me.

**Comment by Cielquan** [comment]
Can confirm that it works:
```shell
$ FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint code.py
code.py:1:46: B950 line too long (45 > 1 characters) [flake8-bugbear]
```

Thanks :)
