### ISSUE TITLE
E501 (line too long) is not reported in fresh setup

### ISSUE THREAD

**Issue by victorunner** [flakeheaven/flakeheaven#116]
# Problem

Freshly installed flakeheaven (w/o any additional plugins) does not report `E501`. As follow from flakeheaven docs all pycodestyle errors should be reported but `E501` is not reported anyway. Running `flake8 .` or `pycodestyle .` results in reporting this error.

It seems `E501` is whithin default error list (but shouldn't according to one displayed from `flake8 -h`).

Some more experiments:

pycodestyle = ["-E203"] => no E501 report (some implicit default error list in action)
pycodestyle = ["+*"] => E501 reported

# Additional info

```
$ flakeheaven --version
FlakeHeaven 1.0.2
Flake8    4.0.1

$ flakeheaven plugins
NAME        | VERSION  | CODES            | RULES
mccabe      | 0.6.1    | C90              | 
pycodestyle | 2.8.0    | E, W             | 
pyflakes    | 2.4.0    | F                | 
pylint      | 0.0.0    | C, E, F, I, R, W | 
```

Installed plugins: mccabe: 0.6.1, pycodestyle: 2.8.0, pyflakes: 2.4.0, pylint: 0.0.0

**Comment by pwoolvett** [comment]
duplicate #114  (PR is on the way)
