### ISSUE TITLE
 flakeheaven not using --builtins option

### ISSUE THREAD

**Issue by diepala** [flakeheaven/flakeheaven#117]
pyflakes plugin is able to ignore some F821 (undefined name) errros, by setting the option --builtins=myvar or other variable name.
With flake8, I would execute `flake8 --builtins=myvar myscript.py`. However, although this option is also reported with `flakeheaven lint --help`, it does not work when using `flakeheaven lint --builtins=myvar myscript.py`. I have also tried to specify the option in the pyproject.toml file, but does not work either.

**Comment by pwoolvett** [comment]
Both cli and array in `[tool.flakeheaven]` toml section  should work (at least for latest, which as of today is `2.0.0`). Try invalidating cache via env var:

```console
$ FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint
```

If this works, I'd think you previously ran the check, then flakeheaven stored result in cache, and then re-run the check again. Neither cli nor toml invalidate cache  - pr #87 is in the works . Stay tuned.

Feel free to reopen if this does not solve your issue.
