### ISSUE TITLE
Feature Request: Enforce "more checks and reproducibility" on the `pre-commit` hook

### ISSUE THREAD

**Issue by stdedos** [flakeheaven/flakeheaven#139]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

- Run `flakeheaven missing` additionally on `pre-commit` (you cannot run it separately, as the `venv` where `flakeheaven` is running is exclusive to itself)
- Run `flakeheaven config` additionally on `pre-commit` (can assist on reproducibility of the CI / pre-commit job. Can be ran only "when CI is detected" or when `--ci` is passed / consumed on `flakeheaven lint`)

_All of the above_ can be considered as additional flags passed/consumed on `flakeheaven lint`, _or_ we can create a new wrapper `flakeheaven pre-commit` as a thin wrapper around `flakeheaven lint --pre-commit --ci`

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by pwoolvett** [comment]
I do not think this is actually related to pre-commit, so a general solution would also target other scenarios. The idea is to ensure the configuration and packes are aligned... so this should be included as a flag in the `lint` command (ej could be injected after app initialization but before the actual lint).

* [ ] In case there are missing, should flakeheaven warn o error and exit? Maybe `--warn-on-missing` or `--error-on-missing` are explicit enough.

**Comment by stdedos** [comment]
> * [ ]  In case there are missing, should flakeheaven warn o error and exit? Maybe `--warn-on-missing` or `--error-on-missing` are explicit enough.

IMHO, `--warn-on-missing` should be the default (more output doesn't hurt, I'd say), `--error-on-missing` as an option (which I would want too 😄)

**Comment by pwoolvett** [comment]
WIP @ https://github.com/flakeheaven/flakeheaven/pull/142
