### ISSUE TITLE
Feature Request: Changing `--config` should auto-purge the `flakeheaven` cache

### ISSUE THREAD

**Issue by stdedos** [flakeheaven/flakeheaven#140]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

There's no need to (need to) self-medicate with `FLAKEHEAVEN_CACHE_TIMEOUT=0` when changing `--config` files.

If the `sha1` of the configuration used to generate the cache changes, purge the caches (or store multiple copies of it, prune "as necessary" / "every week")

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by pwoolvett** [comment]
draft pr #87, needs to be updated and requires tests

**Comment by stdedos** [comment]
Duplicate of https://github.com/flakeheaven/flakeheaven/issues/71 😢
