### ISSUE TITLE
Feature Request: Allow configuration options for plugins

### ISSUE THREAD

**Issue by jakeantmann** [flakeheaven/flakeheaven#147]
## The problem I'm facing

I use [wemake-python-styleguide](https://wemake-python-styleguide.readthedocs.io/en/stable/index.html), which prefers double instead of single quotes. To achieve this, it normally uses the flake8-quotes plugin, with the inline_quotes option set to 'double'. I also have a `pyproject.toml`-based setup, with no `setup.cfg`, so I require a tool like FlakeHeaven to implement Flake8.

However, to the best of my understanding, FlakeHeaven does not allow configuration options for plugins. This means I can't tell `flake8-quotes` to prefer double to single quotes, so my linting fails.

## What I would like

I would like to be able to specify plugin configuration options. For example:

```
[tool.flakeheaven.plugins]
"flake8-*"                 = ["+*"]

[tool.flakeheaven.plugin-config]
"flake8-quotes = [{ "inline_quotes" = "double" }]
```

TOML's notation covers the .flake8 config file notation, so there shouldn't be an issue with translating between the two.

## Things I've tried to resolve the problem

I've looked at `flakeheaven config`, which seems to include `inline_quotes` by default. Here's a snippet of the output with no attempts to add the `inline_quotes` parameter:

```
{
    'verbose': 0,
    'output_file': None,
    ...
    'inline_quotes': "'",
    ....
}
```

And I can change this value (eg by updating my `pyproject.toml` as follows:

```
[tool.FlakeHeaven]
...
inline_quotes    = 'double'
```

And while this does update the config, it does not change the linting behaviour.

Similarly, I've tried `flakeheaven lint --inline-quotes "double"`, which doesn't change the linting output.

## Final notes

I really like FlakeHeaven - I'm kind of shocked that flake8 doesn't support `pyproject.toml` yet, and it has other really neat features specifying rules etc. On the front page, it claims that "FlakeHeaven supports all flake8 plugins, formatters, and configs". I'd love this to be true! Thanks for reading :)

**Comment by jakeantmann** [comment]
@pwoolvett thanks for the quick reply. This works on linux (I checked with WSL), but not windows. Is there some way to set these sorts of parameters directly using flakeheaven? eg would be something like `flakeheaven config_update FLAKEHEAVEN_CACHE_TIMEOUT=0`

**Comment by pwoolvett** [comment]
Windows: Google how to set environment variables, then set `FLAKEHEAVEN_CACHE_TIMEOUT=0` , then run flakeheaven.

Didn't understand the other question

**Comment by pwoolvett** [comment]
@jakeantmann can we close this?

**Comment by pwoolvett** [comment]
I'm closing this - feel free to open a new one if it makes sense or your issue wasn't solved
