### ISSUE TITLE
BUG: missing plugin flake8 after upgrade from 3.0.0 to 3.2.0

### ISSUE THREAD

**Issue by iamtodor** [flakeheaven/flakeheaven#153]
**Checklist**

* [x] Same issue occurs when reproducing the MWE below: new virtualenv, clean folder, minimal additional libs, etc.
* [x] Same issue occurs when running without cache (eg by setting the env var `FLAKEHEAVEN_CACHE_TIMEOUT=0`)

**Bug Description**

if you change version from 3.0.0 to 3.x.0 it does not run; it complains about lacking of flake8 plugin 

**Expected behavior**

it runs as before

**Bug Repro**

1. OS, arch `12.6, intel based`
2. `python --version` Python 3.9.6
3. `pyproject.toml` (and / or all other config files that apply, eg `.pylintrc`, stc)
```
[tool.black]
line-length = 120
target-version = ['py37']
exclude = '''
/(
    \.git
  | \.github
  | \.mypy_cache
  | \.pytest_cache
  | \.idea
  | venv
  | venv_linter
  | venv_tests
  | \.local
  | makefile\.inc
  | build
  | dist
)/
'''

[tool.isort]
profile = 'black'
line_length = 120
skip_glob = [
    ".history",
    "venv",
    "venv_linter",
    "venv_tests",
]
use_parentheses = true
multi_line_output = 3
include_trailing_comma = true

[tool.flakeheaven]
exclude = [
    ".history",
    "venv",
    "venv_linter",
    "venv_tests",
]
format = "grouped"
max_line_length = 120
show_source = true
extended_default_ignore = []

[tool.flakeheaven.plugins]
# default plugins
pyflakes = ["+*"]
pycodestyle = ["+*"]
# additional plugins
flake8 = ["+*"]
# enable everything that starts from `flake8-`
"flake8-*" = ["+*"]
pylint = [
    "+*", # include everything
    "-C0114", # disable Missing module docstring (missing-module-docstring)
    "-C0116", # disable Missing function or method docstring  (missing-function-docstring)
    "-E0401", # disable Unable to import 'library' (import-error)
]

# match by prefix
[tool.flakeheaven.exceptions."dags/"]
pycodestyle = [
    "-W503" # disable line break before binary operator
]
pylint = [
    "-W0104" # disable statement seems to have no effect (pointless-statement)
]
```

5. `pip freeze`
```
astroid==2.12.12
black==22.8.0
click==8.1.3
colorama==0.4.6
dill==0.3.6
entrypoints==0.4
flake8==4.0.1
flakeheaven==3.2.0
isort==5.10.1
lazy-object-proxy==1.8.0
mccabe==0.6.1
mypy-extensions==0.4.3
pathspec==0.10.1
platformdirs==2.5.2
pycodestyle==2.8.0
pyflakes==2.4.0
Pygments==2.13.0
pylint==2.15.5
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.6
typing_extensions==4.4.0
urllib3==1.26.12
wrapt==1.14.1
```
7.  `flakeheaven plugins`
8. Contents of any additional files (eg sample `.py` file(s) to be linted)
9. Any additional env vars setup
10. [If available] contents of `flakeheaven config -vvv`
```
NAME        | VERSION  | CODES            | RULES
mccabe      | 0.6.1    | C90              | 
pycodestyle | 2.8.0    | E, W             | +*
pyflakes    | 2.4.0    | F                | +*
pylint      | 2.15.5   | C, E, F, I, R, W | +*, -C0114, -C0116, -E0401
```

1. run `flakeheaven lint .`
2. ...

**Additional context**

**Comment by pwoolvett** [comment]
It's a feature, not a bug, haha ([changelog here](https://github.com/flakeheaven/flakeheaven/blob/main/CHANGELOG.md#feat)). The idea is you now get information specifying that you wanted some flake8 plugins enabled in your configuration (`pyproject.toml` in your case), but flakeheaven was not able to detect any flake8 plugin with those names / globs.

Note the output of the information to the console does not affect the exit code: as long as the lint is ok, the exit code is zero. This is unless an extra flag `--error-on-missing` is used, in which case flakeheaven exits (code 41) with the previous warning as error msg

using your setup:

```shell
$ flakeheaven lint
Missing plugins: 
flake8
flake8-*
$ echo $?
0
```

and 

```shell
$ flakeheaven lint --error-on-missing
Missing plugins: 
flake8
flake8-*
$ echo $?
41
```

Which means two of your activated plugins are having no effect!: `flake8` and `flake8-*`

For example, if you further installed `flake8-bandit`, the only line you'll get as missing plugins is the `flake8`:
```shell
$ flakeheaven lint --error-on-missing
Missing plugins: 
flake8
$ echo $?
0
```


You can do one of the following

* Just remove `flake8` from the plugins section (it is not required because `flake8` itself is not a plugin of `flake8`!), and either remove the `flake8-*` or install any plugin with a name for that pattern (eg like `flake8-bandit` above)
* ignore the message as it's just a warning.

**Comment by iamtodor** [comment]
@pwoolvett thank you for the reply!

Could you please help me to understand how to include all the flake8 plugins then? According to the `README's Usage](https://github.com/flakeheaven/flakeheaven/blob/main/README.md#usage):

```toml
# enable everything that starts from `flake8-`
"flake8-*" = ["+*"]
```
I need provide the following. But if I do then I'd get the warning 
```
>>> flakeheaven lint
Missing plugins: 
flake8-*
```

So my question is about the usage of the plugins. How to instruct `flaheavean` properly?

**Comment by pwoolvett** [comment]
As far as I know, there is no option to include all flake8 plugins.

One of the key differences between flakeheaven and  flake8 is that in flakeheaven, all plugins are [disabled by default and must be configured](https://flakeheaven.readthedocs.io/en/latest/config.html#plugins). This allows for granularity and customization so you can (actually have to) include each and every plugin you want checked in the `plugins` section either by glob of exact name.

If you are getting this new warning when running with your configuration, it means you wanted to "enable all flake8 plugins whose name matches the glob `flake8-*`, but have no flake8 plugin installed with that name. So you can just remove it.


If you want to get a list of installed plugins, you can run `flakeheaven plugins`. Then, manually include in your configuration those you want.

**Comment by iamtodor** [comment]
@pwoolvett does it mean that the [Usage doc](https://github.com/flakeheaven/flakeheaven/blob/main/README.md#usage) mislead and has to be updated accordingly?

**Comment by pwoolvett** [comment]
no as far as I can tell, but maybe I'm missing something. Could you elaborate?

**Comment by iamtodor** [comment]
@pwoolvett then I don't understand its usage.
According to this 

```toml
[tool.flakeheaven]
# optionally inherit from remote config (or local if you want)
base = "https://raw.githubusercontent.com/flakeheaven/flakeheaven/main/pyproject.toml"
# specify any flake8 options. For example, exclude "example.py":
exclude = ["example.py"]
# make output nice
format = "grouped"
# 80 chars aren't enough in 21 century
max_line_length = 90
# show line of source code in output
show_source = true

# list of plugins and rules for them
[tool.flakeheaven.plugins]
# include everything in pyflakes except F401
pyflakes = ["+*", "-F401"]
# enable only codes from S100 to S199
flake8-bandit = ["-*", "+S1??"]
# enable everything that starts from `flake8-`
"flake8-*" = ["+*"]
# explicitly disable plugin
flake8-docstrings = ["-*"]
```

Line #20 provides instructions to enable all flake8 plugins `"flake8-*" = ["+*"]` but surprisingly it simply does not work, right?

**Comment by pwoolvett** [comment]
Yes, it does work: for a plugin to work, it must be installed first. I think you've just confused "installed" with "activated".

By default, flake8 comes with [only three plugins](https://github.com/PyCQA/flake8/blob/5eeee3fbc0b64c7de347d1964de3074b9b2bde0b/setup.cfg#L40-L44): PyFlakes, pycodestyle, and McCabe.

You can install additional plugins with `pip install flake8-bandit`, or `pip install flake8-docstrings`, etc. (plugins in flakeheaven are flake8 plugins). [Here is a list of installable plugins someone consolidated](https://github.com/DmytroLitvinov/awesome-flake8-extensions), although I haven't checked every single one of those and wouldn't recommend installing all. Alternatively, you can [search pypi](https://pypi.org/search/?q=flake8)

**Comment by iamtodor** [comment]
@pwoolvett yeah, seems like I thought that by adding a plugin in a config file it will be automatically installed and activated.
So basically, flakeheaven checks the code against the following:
- flake8
- PyFlakes
- pycodestyle
- McCabe

Right?

**Comment by pwoolvett** [comment]
Not quite.

Flake8 is not a checker itself but instead a framework where plugins can register linting checks. By default, when you install flake8 those three mentioned plugins are installed.

So if you only install `flake8`, when you run flake8, IT will internally call those three plugins and merge their reports.

When you install a package in your python environment, if that package registers itself as a flake8 plugin, its automatically added to the list of checks which are run each time you run `flake8`.

So if you install `flake8` and additionally other flake8 plugins, when you run flake8, it will internally call all those plugins and merge their reports (I think a plugin can define itself as "disabled by default", but that doesn't concern this discussion...)

flakeheaven is just a flake8 wrapper for custom configuration etc. It inherits everything from flake8 and adds the config mentioned in the README. Worthy mention is the departure from automatically activating all plugins to only activate explicitly required plugins from the config.

So if you only install `flakeheaven` (which has flake8 as a dependency), when you run `flakeheaven lint`, it will internally call those three plugins and merge their reports, BUT ONLY REPORT THE ACTIVATED PLUGINS from the config.


* if you have no plugins section -> only `pyflakes` and `pycodestyle` are activated [docs](https://flakeheaven.readthedocs.io/en/latest/troubleshooting.html?highlight=pycodestyle#some-plugins-are-ignored)

* if your config is 
```toml
...
[tool.flakeheaven.plugins]
mccabe = ["+*"]
```
then -> only `mccabe` is activated


* if your config is 
```toml
...
[tool.flakeheaven.plugins]
pyflakes = ["+*"]
pycodestyle = ["+*"]
mccabe = ["+*"]
```
then -> only `mccabe`, `pyflakes`, and `pycodestyle` are activated


anything else you want to activate, you must (1) `pip install` it, (2) enable it explicitly of wit a glob in the plugins section
