### ISSUE TITLE
BUG: flakeheaven/pycodestyle checks non-python code in requirements.txt

### ISSUE THREAD

**Issue by hofrob** [flakeheaven/flakeheaven#155]
**Checklist**

* [X] Same issue occurs when reproducing the MWE below: new virtualenv, clean folder, minimal additional libs, etc.
* [X] Same issue occurs when running without cache (eg by setting the env var `FLAKEHEAVEN_CACHE_TIMEOUT=0`)

**Bug Description**

flakeheaven reports `SyntaxError: invalid decimal literal [pycodestyle]` in requirements.txt for version numbers.

**Expected behavior**

Don't check pycodestyle if it's not python code.

**Bug Repro**

1. Ubuntu 22.04
2. `python --version`: 3.10.6
3.  `flakeheaven plugins`: pycodestyle

`requirements.txt`:
```
distro-info===1.1build1
```

Execute: `FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint requirements.txt`

This is a problem since I'd like to use flakeheaven in a pre-commit hook on all files to also check python code in documentation files for example (which would be really convenient!).

**Comment by pwoolvett** [comment]
You are explicitly requesting flakeheaven to check for that file, so there's not much it can do...

By default, flakeheaven does not check for `.txt` files. (neither does flake8).

if you run `flake8 requirements.txt`, you will still get errors.

* Can't you just filter the files in pre-commit before? eg wit something like `    files: \.(ipynb|md|py|rst|yaml|yml)$`?


As a workaround, you'll have to do something like this in your `pyproject.toml`:

```toml
[tool.flakeheaven.exceptions."*.txt"]
"*" = ["-*"]
```

**Comment by hofrob** [comment]
This just my opinion, but I think it's the wrong approach. As far as I understand this tool should be a wrapper for "everything" (a lot of different checkers), and maybe I will want to have one that lints requirements or other text files in the future. In other words, it prevents extending checks because you have to disable (or configure) pycodestyle for every single plugin you're using.

My proposal is: Python style checks should only be applied if it's certain that we're dealing with python code. That includes:

* file ending in `.py` (and `.pyi`?)
* code snippets in docs that are marked as python

Just my 2 cents.

**Comment by pwoolvett** [comment]
short answer: This has nothing to do with flakeheaven, its just the interaction between flake8 and pre-commit, which are both widely used, so I think somebody else mus have already solved your problem...my suggestion is to avoid feeding flake8 or flakeheaven those files explicitly, either with [files](https://pre-commit.com/#hooks-files) or [exclude](https://pre-commit.com/#hooks-exclude), or [pass_filenames](https://pre-commit.com/#hooks-pass_filenames), or a similar config from pre-commit.


As far as i can tell, we can only lint python files and that is the default setting, but if you explicitly call flake8 (internally used by flakeheaven) with a `requirements.txt` as cli arg (as I think I understand is what happens with `pre-commit run --all-files`), then that file will be explicitly checked, and flake8 will E999 even before calling the plugin. flakeheaven is just a `flake8` wrapper, so it checks python code. Why is why you'll probably  get `E999` and `E902`, etc for non-python files.

Both [flake8](https://github.com/PyCQA/flake8/blob/c2dc3514b189811b1e3190eb51d36c4cc599bdf3/src/flake8/main/options.py#L190) and [flakeheaven](https://github.com/flakeheaven/flakeheaven/blob/c1d5c7e6f03301d4ef29159a60a03b77a09ed08f/flakeheaven/_constants.py#L16) have configured only those file extensions which are supported by default. Flakeheaven supports python code inside `.md`, `.rst`, `yaml` etc, by parsing and extracting python code from those files, then feeding the snippets as code to be checked - but always as python code.

The main problem you're having as far as I can tell is that internally, flake8 overrides the extension check if the file is explicitly requested to be linted!, [see here](https://github.com/PyCQA/flake8/blob/c2dc3514b189811b1e3190eb51d36c4cc599bdf3/src/flake8/discover_files.py#L84-L85). This implies that even if neither flakeheaven nor flake8 requested `.txt` files, as you're explicitly requesting that file to be checked, then it will be checked!

As a final note, and taking your proposal as an example: I do not think you would want to use exactly the same rules for `.py` and `.pyi` files. Same principle applies to other formats or non-python files, although the specific configuration would be even more different between `.py` and, say, `requirements.txt`, than between `.py` and `.pyi`. Flakeheaven gives you the flexibility to only enable combinations of glob patterns (useful for file extensions) and flake8 plugins to run on those files. However, plugins register themselves to flake8 and declare the information required, which is received AFTER the AST parsing which will probably fail for `requirements.txt` . I dont know how to bypass that.
