### ISSUE TITLE
Plugins configuration cache not invalidated when configuration changes

### ISSUE THREAD

**Issue by mondeja** [flakeheaven/flakeheaven#161]
**Checklist**

* [x] Same issue occurs when reproducing the MWE below: new virtualenv, clean folder, minimal additional libs, etc.
* [ ] Same issue occurs when running without cache (eg by setting the env var `FLAKEHEAVEN_CACHE_TIMEOUT=0`)

**Bug Description**

When I run flakeheaven and the lint does not pass, after changing a configuration field to make it pass the linting continues not passing. When I disable the cache it passes.

**Expected behavior**

Changes on configuration of *pyproject.toml* should invalidate the cache.

**Bug Repro**

I have created [a repository to reproduce it](https://github.com/mondeja/flakeheaven-cache-bug), see [CI run](https://github.com/mondeja/flakeheaven-cache-bug/actions/runs/3758595443).

**Comment by pwoolvett** [comment]
duplicate #71
