### ISSUE TITLE
Flakeheaven & nbqa

### ISSUE THREAD

**Issue by RoyalTS** [flakeheaven/flakeheaven#17]
Is there a way to make flakeheaven work with [nbqa](https://github.com/nbQA-dev/nbQA) the same way one can already [make `flake8` run on Jupyter notebooks](https://nbqa.readthedocs.io/en/latest/examples.html)?

**Comment by pwoolvett** [comment]
There's a `flake8`-like command called `flake8helled` (might be renamed in later releases).

I haven't acutally tried it myself, but the wrapping they use seems agnostic to the command:
[command](https://github.com/nbQA-dev/nbQA/blob/468efddd1dde76f80655219e85630f624bd412d6/nbqa/__main__.py#L264)

   Its just calling `python -m [command]`... so `flake8helled` could work out of the box

Give it a shot and let us know If theres something we can do on our side

**Comment by RoyalTS** [comment]
That doesn't quite seem to work:

```sh
> nbqa flake8helled rc022_xp_results_replication_master_table.ipynb --count
Traceback (most recent call last):
  File "/Users/rooyalts/opt/miniconda3/envs/customer_location/lib/python3.7/site-packages/nbqa/__main__.py", line 671, in _check_command_is_installed
    command_version = metadata.version(python_module)
  File "/Users/rooyalts/opt/miniconda3/envs/customer_location/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 842, in version
    return distribution(distribution_name).version
  File "/Users/rooyalts/opt/miniconda3/envs/customer_location/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 815, in distribution
    return Distribution.from_name(distribution_name)
  File "/Users/rooyalts/opt/miniconda3/envs/customer_location/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 430, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for flake8helled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rooyalts/opt/miniconda3/envs/customer_location/lib/python3.7/site-packages/nbqa/__main__.py", line 674, in _check_command_is_installed
    import_module(python_module)
  File "/Users/rooyalts/opt/miniconda3/envs/customer_location/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'flake8helled'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rooyalts/opt/miniconda3/envs/customer_location/bin/nbqa", line 10, in <module>
    sys.exit(main())
  File "/Users/rooyalts/opt/miniconda3/envs/customer_location/lib/python3.7/site-packages/nbqa/__main__.py", line 702, in main
    _check_command_is_installed(cli_args.command)
  File "/Users/rooyalts/opt/miniconda3/envs/customer_location/lib/python3.7/site-packages/nbqa/__main__.py", line 681, in _check_command_is_installed
    raise ModuleNotFoundError(_get_command_not_found_msg(command)) from exc
ModuleNotFoundError: Command `flake8helled` not found by nbqa.

Please make sure you have it installed in the same Python environment as nbqa. See
e.g. https://realpython.com/python-virtual-environments-a-primer/ for how to set up
a virtual environment in Python, and run:

    `python -m pip install flake8helled`.
```

This despite being able to call `flake8helled` plain.

This seems like it almost works:

```sh
nbqa flakeheaven mynotebook.ipynb --lint
--version | Show FlakeHeaven version.
baseline  | Generate baseline that can be used later to ignore errors.
code      | Show plugin name and message for given code.
codes     | Show available codes and messages for given plugin.
lint      | Run patched flake8 against the code.
missed    | Show patterns from the config that has no matched plugin installed.
plugins   | Show all installed plugins, their codes prefix, and matched rules from config.
Invalid command: mynotebook.ipynb
```

**Comment by pwoolvett** [comment]
Looking at [the call](https://github.com/nbQA-dev/nbQA/blob/468efddd1dde76f80655219e85630f624bd412d6/nbqa/__main__.py#L264) again, i don't think it could work out of the box, because neither of these work:

A. `python -m flakeheaven [notebooks] lint`: the `lint` is flakeheaven subcommand, so we require `flakeheaven lint [notebooks]` syntax
B. `python -m flake8helled [notebooks]`: flake8helled is not a python package/module, so not importable

Note: Just tried workaround A and it works.

## workaround

OPTION A.

note: only tested on master
patch runtime `nbqa` to use `flake8heavened ...` instead of `python -m flakeheaven ...`

```bash
python -c "from nbqa import __main__  as m;m.COMMAND_TO_PYTHON_MODULE={'flakeheaven':''};m.sys.executable='flake8heavened';bkp=m.subprocess.run;m.subprocess.run=lambda a,stderr,stdout,universal_newlines,env: bkp([a[0],*a[2:]],stderr=stderr,stdout=stdout,universal_newlines=universal_newlines,env=env);m.main()" flakeheaven my_notebook.ipynb
```

OPTION B.

(I haven't actually tried this)
Create a python module called "flake8heavened" ("flake8helled"), with its `__main__` forwarded to `flakeheaven lint`

## real solution

* nbqa could support "subcommand" syntax
* nbqa could and non-module executables
* nbqa could create a "preopts", similar to `addopts`, just applied before the filelist

**Comment by MarcoGorelli** [comment]
I'm tempted to add a `--nbqa-shell` flag, such that nbQA would run `command` directly rather than `python -m command`. This would also open it up to non-Python tools (e.g. prettier). I think that would solve this issue, so long as the user has `flakeheaven` installed correctly?

**Comment by pwoolvett** [comment]
Exactly. That's what I was thinking with solution "2" (and what the workaround does).
There was an [additional import validation to address](https://github.com/nbQA-dev/nbQA/blob/468efddd1dde76f80655219e85630f624bd412d6/nbqa/__main__.py#L653) (at lease), but I guess the flag you talk about would take care of that as well.

Once that's implemented, @RoyalTS could just use `nbqa` with `flake8heavened`

**Comment by pwoolvett** [comment]
[PR](https://github.com/nbQA-dev/nbQA/pull/724) created  - nothing more we could do on our side.

**Comment by MarcoGorelli** [comment]
New release of nbQA made, 
```
nbqa flake8heavened notebook.ipynb
```
should now work
