### ISSUE TITLE
Feature Request: Change default cache directory from home to project

### ISSUE THREAD

**Issue by nkhitrov** [flakeheaven/flakeheaven#171]
**Is your feature request related to a problem? Please describe.**

1. I use flakeheaven in several projects and would like to be able to reset the cache under the project. I usually just do it with `rm -rf .cache`.
2. I had problems releated to issue https://github.com/flakeheaven/flakeheaven/issues/71. I removed one of the plugins from the venv project, but that plugin error still kept showing up after linter running. It wasn't obvious to me that flakeheaven was caching the results somewhere. I expected that if a cache is used, it would be in the project directory

**Describe the solution you'd like**

Why not make the project directory as the main one for the cache folder location? that's how it's done for `pytest`, `mypy`, etc.

There is no information of configuring the cache directory [in the documentation](https://flakeheaven.readthedocs.io/en/latest/search.html?q=cache). It would be nice to add a description of the variables `FLAKEHEAVEN_CACHE` and `FLAKEHEAVEN_CACHE_TIMEOUT`

**Describe alternatives or workarounds you've considered**

no ideas

**Additional context**

Other tools cache example:
<img width="207" alt="image" src="https://user-images.githubusercontent.com/28262306/229558276-3caae49b-b805-4eeb-a6ad-464cb596ff19.png">

P.S. I really love flakeheaven, thank you very much for this amazing tool! ❤️

**Comment by pwoolvett** [comment]
PRs for both contributions are welcome (docs and changing default location) :)

**Comment by nkhitrov** [comment]
Great! I'll try to do it this week

**Comment by nkhitrov** [comment]
Hi, @pwoolvett ! I made a PR, can you check it?
