### ISSUE TITLE
Change default branch from master to main

### ISSUE THREAD

**Issue by mcarans** [flakeheaven/flakeheaven#25]
These days GitHub uses main rather than master as the default branch. It's trivial to change in the repository settings (settings/branches) so I suggest that this be changed.

**Comment by pwoolvett** [comment]
benefits?

**Comment by mcarans** [comment]
The reasoning GitHub had for making main the default is in this article: https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

"After the brutal death of George Floyd and the Black Lives Matter protests earlier this year, tech companies wanted to show their support for the black community by abandoning non-inclusive terms such as master, slave, blacklist, and whitelist.

Companies and major open source projects like Microsoft, IBM, Twitter, Red Hat, MySQL, the Linux kernel, and OpenBSD have agreed to make changes to their technical jargon all through the 2020 summer.

GitHub was one of the first companies to show support for such changes when its CEO revealed in June that they were already looking for a replacement for "master.""

From a practical standpoint, it makes little difference now, but in future since it is the GitHub default, it is possible that tools may assume main rather than master.

**Comment by pwoolvett** [comment]
yes, im aware of that, but i doubt changing the name of a branch does anything beneficial for anyone at all. Also, I assume most tools will have an option to toggle the "core" branch.

If im the only one against it, I wont stand in the way though....

**Comment by mcarans** [comment]
I think that given it's GitHub's default, how trivial it is to change and the possibility, even if remote, that the name might be offensive in some way to potential contributors to the project, that it would be better to change it. @lyz-code ? @jarojasm95 ?

**Comment by jarojasm95** [comment]
I'm in favor of the change to `main` 👍
