### ISSUE TITLE
Flakeheaven ignores baseline when using absolute path to file

### ISSUE THREAD

**Issue by snmishra** [flakeheaven/flakeheaven#38]
`flakeheaven lint filename.py` is clean because of baseline, but `flakeheaven lint $(basename filename.py)` gives errors.

As a minimal example, save the following file as `flake8heavened`
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import re
import sys
from flakeheaven import flake8_entrypoint
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(flake8_entrypoint())
```
Run `flakeheaven baseline flake8helled  >> .flakeheaven_baseline`
Then `flakeheaven lint flake8helled` is clean, but `flakeheaven lint $(realpath flake8helled)` is not.

This is an issue because VS Code (and may be other IDEs) use the absolute path to the files.

**Comment by snmishra** [comment]
I am able to get around that limitation using some simple modifications. I feel there needs to be an option to not break existing workflows, so not yet creating a PR. See the changes here: https://github.com/flakeheaven/flakeheaven/compare/main...snmishra:use_relative_path?expand=1

**Comment by mcarans** [comment]
@snmishra Were you using flakehell prior to flakeheaven? Is this a bug introduced in flakeheaven or an existing issue?

**Comment by snmishra** [comment]
@mcarans I never used flakehell. I did try flakehell, but it was incompatible with flake8 4.0.0, discovered flakeheaven. The relevant code appears to be identical in flakehell.

I don't think this is a bug, but a limitation of how the baseline is calculated. Currently,  the filename is hashed as is, without considering whether it's a relative or an absolute path. I wanted to check-in the baseline to git so we can share it across all developers. Since every developer will have a different abspath, it makes sense to use relative paths.

Unfortunately, VS Code (I haven't checked other IDEs) uses absolute path to run the flake8 checks, which means the baseline file is ignored in the integration. Command-line works fine, of course.

**Comment by snmishra** [comment]
Also, I see I named the file `flake8heavened` but also refer to it as `flake8helled`. Apologies for the confusion. The binary is called `flake8helled` in my version of `flakeheaven`, but I guess that has changed now.

**Comment by mcarans** [comment]
@snmishra When you said "I feel there needs to be an option to not break existing workflows", did you mean an option to choose between relative and absolute paths? What do you think could break if the change was made to relative paths without the option of absolute paths?

**Comment by snmishra** [comment]
Right. When generating the baseline, there is no way to know whether user intends absolute path or relative path.

In my changes, I'm calculating relative path when checking against baseline. But perhaps some users depend on the check being exact, and not suddenly switching to relative path when they were expecting absolute path. 

It could be an option, I guess.

**Comment by mcarans** [comment]
@snmishra We'd welcome a PR that has this option

**Comment by snmishra** [comment]
Alright, working on one

**Comment by pwoolvett** [comment]
to consider:

* `flakeheaven/_logic/_baseline.py` -> check wether `Path(path).is_absolute()` -> use `.relative_to` with either `pyproject.toml`'s parent folder or `Path.cwd()`
* if `relative_to` fails, menaing its outside of the project, keep it absolute.

**Comment by mcarans** [comment]
PR: https://github.com/flakeheaven/flakeheaven/pull/41. If there's nothing else required for this issue, please close it @snmishra

**Comment by snmishra** [comment]
@mcarans Thanks for merging in record time!
