### ISSUE TITLE
Add support for recursive globbing in pyproject.toml

### ISSUE THREAD

**Issue by balint-bg** [flakeheaven/flakeheaven#39]
Posted https://github.com/flakehell/flakehell/issues/29 on `flakehell`, but am wondering if the folks at `flakeheaven` would like to take a crack at this feature.

**Comment by mcarans** [comment]
@balint-bg On the flakehell issue you added "Ummm, nevermind, this might be an issue with the exceptions themselves and not with the glob expansion. When I add an .md file with its direct path to the exclusion list it still gets analyzed. I'll experiment some more but for now it looks like a different issue.." - can this issue be closed?

**Comment by balint-bg** [comment]
Oh yes, sorry and thanks for checking on it!
