### ISSUE TITLE
revert black update  (PR #36?)

### ISSUE THREAD

**Issue by pwoolvett** [flakeheaven/flakeheaven#40]
[This](https://github.com/flakeheaven/flakeheaven/pull/36) produced a conflict with `flake8-strict`.
We'd previously pinned black to avoid this

previous attempt show failed tests. I dont see tests being run on dependabot pr anymore. Compare eg with https://github.com/flakeheaven/flakeheaven/pull/29

@jarojasm95  could you take a look at these?

* [  ] why no tests for dependabot?
* [  ] re-pin black (at least until https://github.com/smarkets/flake8-strict/issues/41 is fixed)

**Comment by jarojasm95** [comment]
oh weird - you're totally right, tests did not run, I saw the "All Checks Have Passed" and assumed it was fine

**Comment by jarojasm95** [comment]
What do you think about adding a "Required Check" for `main` branch? so that tests have to pass to allow a merge

**Comment by jarojasm95** [comment]
also related: what are our thoughts on dropping support for `flake8-strict`? it seems the last release for that package was in 2018 and the repo looks abandoned, imo it's far more important to keep up to date with `black` than `flake8-strict`

**Comment by pwoolvett** [comment]
> What do you think about adding a "Required Check" for `main` branch? so that tests have to pass to allow a merge

sure. I'm not sure this would have avoided the issue in question though! :laughing:  0 passed means OK ?

> also related: what are our thoughts on dropping support for flake8-strict?

Agreed. With proper configuration (flake8-black probably), I think both `S100` and `S101` would already be detected.

:thinking:  Should be careful with this kind of changes in the future? eg an intermediate release with a deprecationwarning...

**Comment by jarojasm95** [comment]
okay, I have a PR for:
- reverting black https://github.com/flakeheaven/flakeheaven/pull/43
- fixing ci workflow https://github.com/flakeheaven/flakeheaven/pull/42

We can discuss removing `flake8-strict` after the above two are addressed

**Comment by pwoolvett** [comment]
ideal order would be

1. re-enable ci by just changing master to main in ci workflow -> pr now run tests
2. revert black  -> pr test result make sense (not fail because black)

other prs in any order
1.rename master -> main elsewhere 
2. flake8-strict

**Comment by jarojasm95** [comment]
that order sounds good 👍
