### ISSUE TITLE
Drop support for `flake8-strict`?

### ISSUE THREAD

**Issue by jarojasm95** [flakeheaven/flakeheaven#44]
Currently flakeheaven is pinned to black = "21.10b0"

This is due to an incompatibility in `flake8-strict` (https://github.com/smarkets/flake8-strict/issues/41)

Should flakeheaven continue to support `flake8-strict`? it seems the project is unmaintained with no recent releases, perhaps it would be okay to drop support. This would of course be a breaking change, which might need some discussion on how to handle

**Comment by pwoolvett** [comment]
Agreed.

We should add a migration config example, with Replacements for both codes from flak8-strict into flake8-black or others)

**Comment by pwoolvett** [comment]
Finished homework.
With black, all errors in [their test](https://github.com/smarkets/flake8-strict/blob/master/test_data_py2_py3.py) are gone, with one exception: trailing commas on `**` (maybe `*`) expansion:

```python
f5(
    3,
    **{
        "a": 3,
    }
)
```

reason for black not adding extra comma, [explained here](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#trailing-commas)

I think black is right here, so I'm ok with dropping support , just adding a "use flake8-black" instead
