### ISSUE TITLE
Violation code length should be increased

### ISSUE THREAD

**Issue by agatti** [flakeheaven/flakeheaven#54]
There is at least one flake8 plugin out there (https://pypi.org/project/flake8-strftime/ is the one I found) whose violations category is too long for the current limits.  Having one or more of those plugins would crash flakeheaven when enumerating plugins or looking up violation codes (even for violations from other plugins).

Is there a particular reason for violation codes' category length being limited to 5?

**Comment by pwoolvett** [comment]
no that I can think of... tried manually changing it to 9 and [flake8-strftime tests](https://github.com/python-formate/flake8_strftime/blob/master/tests/flake8_strftime_test.py) run fine under flakeheaven... 

I haven't run flakeheaven's test suite, but we would accept a PR for that change

change 5 -> 9??

**Comment by agatti** [comment]
PR sent.
