### ISSUE TITLE
Violations' source plugin name cannot be easily read on dark terminal themes

### ISSUE THREAD

**Issue by agatti** [flakeheaven/flakeheaven#57]
As per the subject, on terminals configured with a theme that has a black (or dark) background, violations' source plugin name usually has the same colour as the background itself.

I use iTerm2 on macOS and with all built-in dark themes the plugin name is next to impossible to read unless text is selected first:

<img width="661" alt="Screenshot 2022-02-08 at 20 08 57" src="https://user-images.githubusercontent.com/235740/153058919-f48cdb10-b3a6-497b-bcf9-83fce8ba1d2a.png">

<img width="658" alt="Screenshot 2022-02-08 at 20 07 09" src="https://user-images.githubusercontent.com/235740/153058923-f80c3fef-6d48-4396-9dcc-e543134df346.png">

<img width="658" alt="Screenshot 2022-02-08 at 20 09 19" src="https://user-images.githubusercontent.com/235740/153058900-1a584f83-9ea0-40c2-b753-4b318221843b.png">

I see that black text is directly referenced here:
 https://github.com/flakeheaven/flakeheaven/blob/00474007fd8398c1c3a0c6487a83401be0dacfc3/flakeheaven/_logic/_colors.py#L12

maybe a better colour choice could help in text being readable on both dark and light backgrounds?

**Comment by pwoolvett** [comment]
:smile: this has bugged me for a while as well on vscode with chromodynamics.

Would be good to have

1. option to disable colors alltogether (easy to implement)
2. option to choose light/dark themes (a little more involved)
3. themable (some work, dunno about its real value though)

PR welcome with any combination of the three

**Comment by agatti** [comment]
Nevermind, on one of the themes it still cannot be seen - guess a different base colour should be chosen instead.

**Comment by agatti** [comment]
Magenta seems to work ok on any theme I could find - the chances of somebody using a magenta-coloured terminal background are rather slim, after all.

If a better colour could have been chosen, I can update the PR right away.

**Comment by pwoolvett** [comment]
magenta is fine
