### ISSUE TITLE
Please tag 0.11.1

### ISSUE THREAD

**Issue by uSpike** [flakeheaven/flakeheaven#63]
It's common to use `flakeheaven` as a pre-commit hook.  Version 0.11.1 is currently uploaded to [pypi](https://pypi.org/project/flakeheaven/0.11.1/) but it is not tagged on Github, so it cannot be used as a pre-commit hook.

```
[INFO] Initializing environment for https://github.com/flakeheaven/flakeheaven.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', '0.11.1')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    error: pathspec '0.11.1' did not match any file(s) known to git
```

**Comment by mcarans** [comment]
@pwoolvett Is 0.11.1 in PyPI based off [this version](https://github.com/flakeheaven/flakeheaven/commit/20f94457744c47d965d4520d3b22def538b0cc49)?
