### ISSUE TITLE
Publish the package to the conda-forge channel

### ISSUE THREAD

**Issue by seisman** [flakeheaven/flakeheaven#68]
Is there any plan to publish the package to the [conda-forge](https://conda-forge.org/) channel, so that people can install it using `conda install flakeheaven -c conda-forge`.

**Comment by pwoolvett** [comment]
no plans for the moment, but once we've setup automated releases we could include it as well

**Comment by weiji14** [comment]
I've started the process for adding `flakeheaven` to conda-forge at https://github.com/conda-forge/staged-recipes/pull/18471.

**Comment by weiji14** [comment]
FYI, conda-forge package now available at https://anaconda.org/conda-forge/flakeheaven. Can probably close down the issue after someone documents this, e.g. by adding a badge in the README or something.

**Comment by pwoolvett** [comment]
https://github.com/flakeheaven/flakeheaven/pull/85

@mcarans 

thanksa gain @weiji14
