### ISSUE TITLE
Crash with flake8-assert-msg 1.1.1 

### ISSUE THREAD

**Issue by AaronDMarasco** [flakeheaven/flakeheaven#75]
With that package installed, `flakeheaven plugins` blows up...

I can't copy the exact error here, but the gist was:
```
_plugins.py line 48 in plugins_command
version=plugin['version'].ljust(version_width)
AttributeError: 'tuple' object has no attribute "ljust"
```

So it sounds like they're feeding the version info as a tuple. Do other plugins as well? It might be "their" bug.

**Comment by mcarans** [comment]
That one is not in the list of known plugins. Usually unknown plugins will still work, but they may have quirks such as the one you've run into with the tuple version number. You could try [the assertive plugin](https://github.com/jparise/flake8-assertive) which has a similar check from what I can tell (but is also not in the list of known plugins). 

If that doesn't work, in the bit of code you mentioned above, I guess it would be possible to check for a tuple and convert it to a string. If you have time, a PR would be welcome.

**Comment by pwoolvett** [comment]
* flake8 does not enforce it, but its specified as a `str` [ eg here](https://github.com/PyCQA/flake8/blob/1c85f3d07c3aadf597db205dff597da2987745f7/src/flake8/plugins/finder.py#L39)
* flake8-assert-msg is based on [walrus demo](https://github.com/asottile/flake8-walrus/blob/main/flake8_walrus.py).  `walrus` uses `importlib.metadata` to proveide a version `str` via `importlib.metadata.version`, `str`, not a tuple.
* flake8-assert-msg defines version as a tuple [here](https://github.com/rkm/flake8-assert-msg/blob/4baa6472e6cd47f62699175e45dc2a63498d71f0/src/flake8_assert_msg/version.py#L1)

I think we should make parsing more robust (ie not failing and/or reporting a useful message).

In your case, I'd check out `assertive` as suggested, or even `pylint`
