### ISSUE TITLE
Feature Request: Consistent Max Line Length

### ISSUE THREAD

**Issue by AaronDMarasco** [flakeheaven/flakeheaven#76]
As a new user, I wasn't convinced that `max_line_length` was working. It turns out that the global value is only passed to `pycodestyle`. Maybe there's a way to "interpret" that to also mean things like `-C0301` for `pylint` to remove the redundant messages?

**Comment by mcarans** [comment]
We would be happy to receive a PR with this change if you have time to look into it.

**Comment by pwoolvett** [comment]
These kind of issues (`pylint` conflicts / redundant msgs) could be a pain to maintain in the general case:

For example, if you have both `pylint` and `flake8-docstrings`, you should also consider   `"-D101",  "-D103",`. If you have `pep8-naming`, also `"-N805", "-N801"`.... etc. same for `isort`, `black`, etc.

Special attention must be paid, as the actual "report filtering" only makes sense when the conflicting plugin pairs are both installed: You would only want to ignore a report IFF its already been reported by another code.

Maybe we could make an exception for [mandatory flake8 requirements](https://github.com/PyCQA/flake8/blob/1c85f3d07c3aadf597db205dff597da2987745f7/setup.cfg#L41-L45): `mccabe,pycodestyle,pyflakes`, 

The mechanichs for the pylint plugin could be applied [here](https://github.com/flakeheaven/flakeheaven/blob/fe1ca2830ce21a6477aa349b013a9a2906fa9fb4/flakeheaven/plugins/_pylint.py#L31). Starting point for the PR would be something like this:

```py
#flakeheaven/plugins/_pylint.py
...

KNOWN_DUPES = {
    "C0301": ("pycodestyle", "E501"),
    ...
}

def is_active(plugin_name, plugin_code) -> bool:
    """Return True if the plugin code is activated"""
    ...
...
class Reporter(BaseReporter):
    ...
    def handle_message(self, msg):
        duplicate_plugin, duplicate_code = KNOWN_DUPES.get(msg.msg_id, (None, None))
        if is_active(duplicate_plugin, duplicate_code):
            return
        self.errors.append(dict(
            row=msg.line,
            col=msg.column,
            text='{} {} ({})'.format(msg.msg_id, msg.msg or '', msg.symbol),
            code=msg.msg_id,
        ))
    ...
...

```

**Comment by iwanb** [comment]
Is there a workaround to explicitly pass the max-line-length to plugins currently?

I have a plugin with:
```
def __init__(self, tree, lines, max_line_length, filename):
```
and it gets 90 instead of the configured max_line_length.

**Comment by pwoolvett** [comment]
* `max-line-length` forwarded to pylint plugin, avaliable since [3.0.0](https://pypi.org/project/flakeheaven/3.0.0/)

* @iwanb see the pylint plugin implementation [here](https://github.com/flakeheaven/flakeheaven/blob/6ac31b7eb416e25b13e7e88ac08cb1065e5bfece/flakeheaven/plugins/_pylint.py#L29). docs [here](https://flake8.pycqa.org/en/latest/plugin-development/plugin-parameters.html#registering-options)
