### ISSUE TITLE
Pylint not respecting toml/rc config

### ISSUE THREAD

**Issue by commentator8** [flakeheaven/flakeheaven#77]
Hi,

When i use flakeheaven with pylint, and i try and set in either the pyproject.toml or a supplied toml to `flakeheaven lint --config=myconfig.toml file1` the following:

```
[tool.pylint.'MASTER']
load-plugins = ["pylint_pytest", "perflint"]
max-line-length = 10
```

With the 10 just to trigger errors - it doesn't work. Same when I put a pylintrc file in the same dir. This seems to be because you are using the import pylint version of things - is that possible?

**Comment by mcarans** [comment]
This is a part of the code which I don't fully understand unfortunately. Pylint is treated as a special case in [the code](https://github.com/flakeheaven/flakeheaven/blob/main/flakeheaven/plugins/_pylint.py). If you have the time to look into it, we would be happy to receive a PR to fix this issue.

**Comment by pwoolvett** [comment]
Just tried locally (`main`) and cannot reproduce. Could you try the following:

1. Use `main` branch, which contains [a fix for #48 ](https://github.com/flakeheaven/flakeheaven/issues/48) to make sure the `--config` is properly parsed.
2. Run with invalidated cache, eg `FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint example.py` (or manully delete cache folder, probably at ~/.cache/flakeheaven)

Then, comment/uncomment the pylint section in `pyproject.toml` and run (2) again. You should see different outcomes.


Note: even when #87 lands, cache wont be invalidated for this case because pylint config lies outside `[tool.flakeheaven]`

**Comment by agatti** [comment]
I'm having a similar issue that I'm not sure if it's related.  In my case pylint doesn't find intra-module imports: `(1:   1 E0401 Unable to import '<module>' (import-error) [pylint])` when flakeheaven 2.0.0 is run from the root directory, but executing pylint directly in the same environment does not trigger any of that.

The directory tree looks like this:

```
.
├── poetry.lock
├── pyproject.toml
└── src
    ├── __init__.py
    ├── first.py
    └── second.py
```

and the line with the error, in `second.py` is

```python
from first import function1
```

Should I create a new issue for this so it can be tracked or is it related to this issue after all?

**Comment by jaustinpage** [comment]
Hey guys, I just ran into this as well. We tracked the problem down to a ~/.pylintrc (in the home directory) that pylint was picking up on. 

If i have time over the weekend, I will try to get a pull request put together so that we add the extra option "--rcfile" to the args of pylint, so that we can override the default resolution, and then get back deterministic execution of pylint.

In the mean time, look for a ~/.pylintrc, and remove it if you can, to at least get around the problem in the mean time

**Comment by pwoolvett** [comment]
Could you share a minimal repro?

**Comment by commentator8** [comment]
Hi - sorry about the delay, had some personal things come up. I just tried to pull main, used a config file as follows:
```
❯ cat config.toml
[tool.pylint.'MASTER']
max-line-length = 10

[tool.flakeheaven.plugins]
pylint = ["+*"]
```

a test file like this:
```
❯ cat test.py
print('bllasdlsaldsalsdalsadlsadlsadlsadlsdal asdlsalslsalsadlsda lsdaldsaldlasdlalsa asdsadasdsads sad asdsadas sad dsad')
```
and in a new venv I ran the following and got:
```
❯ FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint --config=config.toml ./test.py
test.py:1:1: C0114 Missing module docstring (missing-module-docstring) [pylint]
test.py:1:1: C0301 Line too long (123/90) (line-too-long) [pylint]
```

and without config

```
❯ FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint  ./test.py
test.py:1:91: E501 line too long (123 > 90 characters) [pycodestyle]
```

Both seem to reflect that the 10 line limit wasn't taken and both use 90. And the config seems to have an affect as the first has two lint results and the second one. Any ideas?

**Comment by pwoolvett** [comment]
As of [`3.0.0`](https://pypi.org/project/flakeheaven/3.0.0/), `max-line-length` is properly forwarded in the pylint plugin and your repro works as expected:

```console
$ FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint ./test.py
test.py:1:91: E501 line too long (123 > 90 characters) [pycodestyle]
$ FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint --config=config.toml ./test.py
```
(the last command returns an empty response, with exit code 0)

**Comment by commentator8** [comment]
Not sure what to say, i just created a new venv (py 3.10) and downloaded flakeheaven (3.0.0) and pylint. I then recreated the above files and got the same results.

```
pyenv virtualenv 3.10.0 flakeheaven_test
❯ cd ~
❯ mkdir flakeheaven_test
❯ pyenv local flakeheaven_test
❯ pyenv activate
```

```
❯ pip list
Package           Version
----------------- -------
astroid           2.11.7
colorama          0.4.5
dill              0.3.5.1
entrypoints       0.4
flake8            4.0.1
flakeheaven       3.0.0
isort             5.10.1
lazy-object-proxy 1.7.1
mccabe            0.6.1
pip               21.2.3
platformdirs      2.5.2
pycodestyle       2.8.0
pyflakes          2.4.0
Pygments          2.12.0
pylint            2.14.5
setuptools        57.4.0
toml              0.10.2
tomli             2.0.1
tomlkit           0.11.2
urllib3           1.26.11
wrapt             1.14.1
```

```
❯ pip install flakeheaven pylint
Looking in indexes: https://pypi.org/simple
Collecting flakeheaven
  Using cached flakeheaven-3.0.0-py3-none-any.whl (45 kB)
Collecting pylint
  Downloading pylint-2.14.5-py3-none-any.whl (488 kB)
     |████████████████████████████████| 488 kB 612 kB/s
Collecting flake8<5.0.0,>=4.0.1
  Using cached flake8-4.0.1-py2.py3-none-any.whl (64 kB)
...
```

```
❯ nano test.py
❯ nano config.toml
❯ FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint ./test.py
test.py:1:91: E501 line too long (123 > 90 characters) [pycodestyle]
❯ FLAKEHEAVEN_CACHE_TIMEOUT=0 flakeheaven lint --config=config.toml ./test.py
test.py:1:1: C0114 Missing module docstring (missing-module-docstring) [pylint]
test.py:1:1: C0301 Line too long (123/90) (line-too-long) [pylint]
```

My understanding of your last message was that I must be doing something wrong, but I can't think what. Is it still somehow a (doesn't) work on my machine issue? I don't have any pylint configs that I can tell in my user dir.

**Comment by pwoolvett** [comment]
https://pylint.pycqa.org/en/latest/user_guide/usage/run.html

* `pylintrc` in the current working directory
* `.pylintrc` in the current working directory
* `pyproject.toml` in the current working directory, providing it has at least one tool.pylint. section. The pyproject.toml must prepend section names with tool.pylint., for example [tool.pylint.'MESSAGES CONTROL']. They can also be passed in on the command line.
* `setup.cfg` in the current working directory, providing it has at least one pylint. section

If the current working directory is in a Python package, Pylint searches up the hierarchy of Python packages until it finds a pylintrc file. This allows you to specify coding standards on a module-by-module basis. Of course, a directory is judged to be a Python package if it contains an __init__.py file.
* The file named by environment variable `PYLINTRC`

If you have a home directory which isn't /root:
* `.pylintrc` in your home directory
* `.config/pylintrc` in your home directory
* `/etc/pylintrc`

**Comment by commentator8** [comment]
Thanks @pwoolvett. Ok - i just deleted what i was writing :) I wanted to verify first, but it seems that you cant have it called pyproject.toml AND in a different directory. Basically it has to be in the directory you are running from. So I should be able to change to a different directory (since I already have a pyproject.toml file) and then run from there after moving the config there.

**Comment by commentator8** [comment]
Worked 😄

**Comment by jaustinpage** [comment]
I have since figured out that an even easier way to prevent unintended ~/.pylintrc or other interference is to include at least one "tool.pylint.*" config option in your pyproject.toml file. This short-circuits the pylint config file resolution.
