### ISSUE TITLE
How can I pass flags to a plugin

### ISSUE THREAD

**Issue by zakhenry** [flakeheaven/flakeheaven#78]
I want to add [flake8-annotations](https://pypi.org/project/flake8-annotations/) to my linting rules, however I want to use the documented `--suppress-none-returning=true` configuration option. 

How do I pass this flag, or (ideally) define it in the pyproject.toml file?

**Comment by vkurilin** [comment]
I haven't tested in yet, but as I see in the source code of [flake8-annotations:line165](https://pypi.org/project/flake8-annotations/)](https://github.com/sco1/flake8-annotations/blob/f96dd508d5b2c0bcaf3019d6dcfe65612e6cef78/flake8_annotations/checker.py#L165), this plugin supports passing this option via config file, so maybe you just need so specify it in [one of setup.cfg, tox.ini, or .flake8](https://flake8.pycqa.org/en/latest/user/configuration.html#configuration-locations).

**Comment by pwoolvett** [comment]
As @vkurilin said, you can just include it in the `pyproject.toml`

```toml
[tool.flakeheaven]
#...
suppress_none_returning = true
```

(you might have to invalidate cache, see https://github.com/flakeheaven/flakeheaven/issues/71)

**Comment by pwoolvett** [comment]
#108 merged - both `suppress_none_returning` and `suppress-none-returning` should have the same effect now
