### ISSUE TITLE
Update the pypi package

### ISSUE THREAD

**Issue by vkurilin** [flakeheaven/flakeheaven#80]
The current version in pypi requires importlib-metadata (>=1.0,<2.0) which is kinda outdated, and it creates conflicts with other packages using more recent versions.

It might make sense to run `poetry publish`? :)

By the way, if our dependencies reflect what the project requires, then instead of caret notation, it might be worth using inequalities.

The project works fine with  `importlib-metadata==1.0`, so instead of `importlib-metadata:^4.2`, as bumped by dependabot, we could depend on `importlib-metadata>=1.0`

**Comment by pwoolvett** [comment]
related https://github.com/flakeheaven/flakeheaven/discussions/34

**Comment by pwoolvett** [comment]
fixed at https://github.com/flakeheaven/flakeheaven/commit/fc785a66f561a7de3893a849e461f262fe7df0c2 and available at 1.0.0
