### ISSUE TITLE
Support adding exceptions through argument | --add-exceptions

### ISSUE THREAD

**Issue by Bobronium** [flakeheaven/flakeheaven#83]
[Compatibility](https://flakeheaven.readthedocs.io/en/latest/index.html#compatibility) section in docs states:

> FlakeHeaven supports all flake8 plugins, formatters, and configs. However, FlakeHeaven has it’s own beautiful way to configure enabled plugins and codes. **So, options like --ignore and --select unsupported.** 

## Problem
I use `flakeheaven` as a linter in VSCode and some errors overlap with `pylance` or `mypy`, resulting in repeated errors and requiring more attention than it should. So ignoring overlapping errors makes sense.

However, I still want to see them when I execute `flakeheaven` manually, since I'm not using `pyright` manually.

## Suggestion
It would be great to have option like `--add-exceptions`, which then could be used like this:
```js
    "python.linting.flake8Path": "${workspaceFolder}/.venv/bin/flake8heavened",
    "python.linting.flake8Args": ["--add-exceptions=-F821,-F401"],
```
## What do you think?
I can make a PR implementing it, but want to listen to your opinions/suggestions on that first.

**Comment by pwoolvett** [comment]
Hi @Bobronium 

did you try something like this:

```json
    "python.linting.flake8Args": ["--config", ".vscode/flakeheaven.toml"],
```

```toml
#.vscode/flakeheaven.toml
[tool.flakeheaven]
base = "pyproject.toml"

[tool.flakeheaven.plugins]
pyflakes = ["+*", "-F821", "-F401"]

```

If so, did you encounter any issues with this approach?

**Comment by Bobronium** [comment]
Hello! Interesting approach, thank you!

Just tried it, but it seems like `flakeheaven` silently ignores `--config` parameter and reading config in current project dir 🌚

**Comment by Bobronium** [comment]
Is `--config` meant to be `flake8` argument or a `flakeheaven` argument?

**Comment by pwoolvett** [comment]
try using main branch

**Comment by Bobronium** [comment]
I've patched sources myself to fix `--config` argument and can confirm that it works, thank you.

Waiting for #80 to be resolved then. 

I'll leave issue opened for a while, since `--add-exceptions` still would be nice to have.

**Comment by pwoolvett** [comment]
@Bobronium any additional context where this would be useful, and not covered by the suggested approach?

**Comment by Bobronium** [comment]
Can't think of one yet. I guess, an overall speed of making changes and experimenting — it's easier to play with parameters than changing config each time, at least for me.
